console.log("WORDLIST.JS LOADED (diagnostic)");

window.ANSWERS = [
  "ABAFT","ABEAM","ABOUT","ABORT","ALMAR","ALNAV","ALPHA","AIMHI","ARMYGI","COAST","SPFOR",
  "APORT","ARMED","ARMOR","ARMYS","ARTIE","ATSEA","AVAST","AWASH",
  "BEACH","BELAY","BENNY","BILGE","BINGO","BULGE","BOLTER","BOSUN","BRASS","BREAK","BUDDY",
  "BUNKS","CABLE","CAULK","CHIEF","CHOCKS","CLEAT","COMMO","CONUS","COAGD",
  "CRATS","CYBER",
  "DAVIT","DELTA","DIVER","DIVES","DOCKS","DRIFT","DRILL",
  "ECLUB","EXFIL",
  "FIGHT","FIRST","FLEET","FLANK","FLIGHT","FLOOD","FORCE","FRAGO","FUBAR",
  "GATES","GEDUNK","GIZMO","GRIDS","GUARD","GUMBY",
  "HATCH","HELOS","HEROS","HITCH","HOOCH",
  "HOTEL","HURRY",
  "INDIA","INFIL",
  "JEEPS",
  "KABAR","KHAKI","KLICS","KOREA",
  "LANDS","LANCE","LEAVE","LIFER","LIBBO",
  "MAJOR","MARINE","MEDIC","MILES","MIDDY","MOTOR","MRATS",
  "NAVAL","NAVYS","NATGD",
  "OCLUB","OPORD","OPSEC","ORBIT","ORDER",
  "PACKS","PATROL","PEACE","PIECE","PILOT","PORTS","POWER",
  "RADAR","RANGE","RECON","ROMEO","ROGER",
  "SALTY","SARGE","SCUBA","SEALS","SERVE","SHAVE","SHIPS","SHORT","SIGHT","SIXBY",
  "SKATE","SKOSH","SLIDE","SMEAC","SMOKE","SNAFU","SONAR","SPACE","STAGE","STEAM",
  "STERN","SUPRA","SWORD",
  "TANGO","TEAMS","TIGHT","TRAIN","TROPS","TRUCK",
  "UBOAT","UNITS","USAFS","USAGE","USUAL","USVET",
  "VALOR","WATCH","WATER","WEIGH","WILCO","WINCH","WOUND"
];

window.VALID_WORDS = window.ANSWERS.slice();

console.log("ANSWERS COUNT:", window.ANSWERS.length);