// wordlist.js
// Veteran-themed ANSWERS list (used for daily target)
// NOTE: All entries must be EXACTLY 5 letters, A–Z only, uppercase.

console.log("wordlist.js loaded (diagnostic)");

window.ANSWERS = [
  "ABAFT","ABEAM","ABOUT","ABORT","ALMAR","ALNAV","ALPHA","APORT","ARMED","ARMOR",
  "ARMYS","ARTIE","ATSEA","AVAST","AWASH","BEACH","BELAY","BENNY","BILGE","BINGO",
  "BLIVET","BOLTER","BOSUN","BRASS","BRAVE","BREAK","BUDDY","BUNKS","CABLE","CAULK",
  "CHIEF","CHOCK","CLEAT","COMMO","CONUS","COAST","COAGD","CRATS","CYBER","DAVIT",
  "DELTA","DIVER","DIVES","DOCKS","DRIFT","DRILL","EAGLE","ECLUB","EXFIL","FIGHT",
  "FIRST","FLEET","FLANK","FLIGHT","FLOOD","FORCE","FRAGO","FUBAR","GATES","GEDUNK",
  "GIZMO","GRIDS","GUARD","GUMBY","HATCH","HELOS","HEROS","HITCH","HOOCH","HONOR",
  "HOTEL","HURRY","INDIA","INFIL","JEEPS","KABAR","KHAKI","KLICS","KOREA","LANDS",
  "LANCE","LEAVE","LIFER","LIBBO","MAJOR","MARIN","MEDIC","MILES","MIDDY","MOTOR",
  "MRATS","NAVAL","NAVYS","NATGD","OCLUB","OPORD","OPSEC","ORBIT","ORDER","PACKS",
  "PATRO","PEACE","PIECE","PILOT","PORTS","POWER","RADAR","RANGE","RECON","ROMEO",
  "ROGER","SALTY","SARGE","SCUBA","SEALS","SERVE","SHAVE","SHIPS","SHORT","SIGHT",
  "SIXBY","SKATE","SKOSH","SLIDE","SMEAC","SMOKE","SNAFU","SONAR","SPACE","STAGE",
  "STEAM","STERN","SUPRA","SWORD","TANGO","TEAMS","TIGHT","TRAIN","TROPS","TRUCK",
  "UBOAT","UNITS","USAFS","USVET","VALOR","WATCH","WATER","WEIGH","WILCO","WINCH",
  "WOUND","COVER","NCOIC","PADRE","RACKS","SALTY","SNUFF","UNSAT","SPACE","DRONE",
];

// IMPORTANT: Initialize VALID_WORDS with answers so every answer is always a valid guess.
window.VALID_WORDS = window.ANSWERS.slice();

console.log("ANSWERS COUNT:", window.ANSWERS.length);